### ISSUE TITLE
Senaste administratör lathunder ligger på en plats och är godkänd/editerade.

### ISSUE THREAD

**Issue by RayTimlin** [malmomap/karta#8]

**Comment by RayTimlin** [comment]
Mari (?) har skapat en ny mapp i G:\Projekt\mMap-Forvaltning (annmun2)\Karta\Lathundar nivå 1. Har uppdaterade med en slags lathund av hur man kan installera senaste SSM version

**Comment by RayTimlin** [comment]
Har lämnat in  befintliga lathunder till nivå 2 och 3 (trots det är inte något vi ska jobba emot till hösten). Har också uppdatera excel sammanställning fil som finns på  G:\Projekt\mMap-Forvaltning (annmun2)\Karta

**Comment by MariAden** [comment]
Härligt, jag har tagit excel-sammanställningen av lathundar för att använda i SKU-gruppen.
